printWidth: 120
tabWidth: 2
useTabs: false

overrides:
  - files: "*.java"
    options:
      tabWidth: 4
  - files: "*.md"
    options:
      proseWrap: always
  - files: "*.xml"
    options:
      tabWidth: 4
      xmlWhitespaceSensitivity: ignore
